# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
      run: export PYTHONPATH=$(git rev-parse --show-toplevel)

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv sync --dev

    - name: Format with Black
      run: pipenv run black --check .

    - name: Lint with Pylint
      run: pipenv run pylint -E *.py

    - name: Static type checking with mypy
      run: pipenv run mypy .

    - name: Unit tests + doctests with pytest
      run: |
        pipenv run pytest -v --doctest-modules .
